server:
  port: 8080

spring:
  application:
    name: rate-limiter-service
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

rate-limiter:
  enabled: true
  type: in-memory  # in-memory or redis
  algorithm: fixed-window  # fixed-window, sliding-log, sliding-counter, token-bucket, leaky-bucket
  rules:
    - path: /hello
      limit: 5
      window-seconds: 60
  default-rule:
    limit: 10
    window-seconds: 60
